### ISSUE TITLE
Does not build on i386

### ISSUE THREAD

**Issue by arrowd** [GaloisInc/libBF-hs#2]
```
Building library for libBF-0.5.1..
[1 of 3] Compiling LibBF.Opts       ( /wrkdirs/usr/ports/security/hs-cryptol/work/cryptol-2.9.0/dist-newstyle/build/i386-freebsd/ghc-8.10.1/libBF-0.5.1/build/LibBF/Opts.hs, /wrkdirs/usr/ports/security/hs-cryptol/work/cryptol-2.9.0

src/LibBF/Opts.hsc:174:23: error:
    * Couldn't match type `Word64' with `Word32'
      Expected type: LimbT
        Actual type: Word64
    * In the first argument of `ShowFmt', namely `n'
      In the expression: ShowFmt n 0
      In an equation for `showFixed': showFixed n = ShowFmt n 0
    |
174 | showFixed n = ShowFmt n #{const BF_FTOA_FORMAT_FIXED}
    |                       ^

src/LibBF/Opts.hsc:178:22: error:
    * Couldn't match type `Word64' with `Word32'
      Expected type: LimbT
        Actual type: Word64
    * In the first argument of `ShowFmt', namely `n'
      In the expression: ShowFmt n 65536
      In an equation for `showFrac': showFrac n = ShowFmt n 65536
    |
178 | showFrac n = ShowFmt n #{const BF_FTOA_FORMAT_FRAC}
    |                      ^
```

**Comment by robdockins** [comment]
I believe this should be fixed via #8, but I don't have easy access to a 32-bit system to check.

**Comment by arrowd** [comment]
This problem was indeed fixed, but there is another one:

```
src/LibBF/Mutable.hsc:455:56: error:
    * Couldn't match type `Int64' with `Int32'
      Expected type: SLimbT
        Actual type: Int64
    * In the second argument of `bf_mul_2exp', namely `e'
      In the expression: bf_mul_2exp out e p f
      In the first argument of `bf1', namely
        `(\ out -> bf_mul_2exp out e p f)'
    |
455 | fmul2Exp (BFOpts p f) e = bf1 (\out -> bf_mul_2exp out e p f)
    |                                                        ^

```

**Comment by robdockins** [comment]
Bummer.  I'll see if I can get access to a 32-bit system and get this figured out.

**Comment by arrowd** [comment]
Any progress on this?

**Comment by robdockins** [comment]
No yet, I'm afraid.

**Comment by arrowd** [comment]
This is still a problem not only for i386, but also aarch64: https://cgit.freebsd.org/ports/commit/?id=01049111d77ab4f8a1c0b59d8cb965414b9a2a0d

**Comment by robdockins** [comment]
I'll make another attempt to get this building, but it will be especially hard for me to test ARM builds.

**Comment by robdockins** [comment]
I think that #16 has fixed this issue, although I don't have ready access to a suitable system to test.  Would it be possible for you to run a build before I cut a new Hackage release?

**Comment by arrowd** [comment]
Repository HEAD seems to work for me on FreeBSD 12.2 i386.

**Comment by tilowiklundSensmetry** [comment]
This is also breaking builds for some of my colleagues on M1-macs.

**Comment by RyanGlScott** [comment]
Since this appears to be addressed on `master`, I think this just needs someone to upload a new Hackage release.

**Comment by tilowiklundSensmetry** [comment]
I don't think the fix in master will work on 64bit non-x86_64 architectures (e.g. ARM64). The issue arises from the way 64bit architecture is identified in libbf (see [here](https://github.com/GaloisInc/libBF-hs/blob/8ca1ffbea5df2fc572934ffc9f21e360661e0969/libbf-2020-01-19/libbf.h#L30)).

**Comment by robdockins** [comment]
Oh, that is unfortunate. I'm actually not sure what's a good semi-portable way to query 32 vs 64 bit machine words in C.

**Comment by tilowiklundSensmetry** [comment]
I think something like this may work  but I have not had the opportunity to test yet.

**Comment by RyanGlScott** [comment]
Is this still an issue as of [`libBF-0.6.7`](https://hackage.haskell.org/package/libBF-0.6.7)? In #31, I was able to compile the library on 32-bit Linux without running into any build failures. (There are other problems with running the test suite, as reported in #26, but I think it at least compiles now.)

**Comment by RyanGlScott** [comment]
#31 adds a 32-bit Linux CI configuration, which should ensure that it continues to work going forward. As such, I'll close this. Please re-open if I've missed something.
